name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all history and metadata
      run: |
        git checkout -b pr
        git branch -f main origin/main

    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - run: pip3 install wpiformat==2025.33
    - run: wpiformat

    - name: Verify wpiformat made no changes
      run: git --no-pager diff --exit-code HEAD

  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install OpenGL
      run: |
        sudo apt-get update -q
        sudo apt-get install -y \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libssh-dev \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev
    - run: cmake -B build -S .
    - run: cmake --build build
